# Generated by Django 3.2.4 on 2021-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='Introduce',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pub_date',
            field=models.DateTimeField(default=''),
        ),
    ]
