# Generated by Django 3.2.4 on 2021-06-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_portfolio_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Age',
            field=models.IntegerField(default='3', verbose_name=''),
        ),
    ]
