# Generated by Django 3.2.4 on 2021-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_alter_portfolio_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='pub_date',
            field=models.DateTimeField(default='', max_length=50),
        ),
    ]
