# Generated by Django 3.2.4 on 2021-06-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_alter_portfolio_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='Introduce',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pub_date',
        ),
    ]
